In [1]:
import tensorflow as tf
from tensorflow import keras
from keras.datasets import fashion_mnist
from tensorflow.keras import datasets
from keras.layers import Input
import numpy as np
from sklearn.metrics import confusion_matrix, classification_report, precision_score, recall_score
from keras.models import Sequential
from keras.layers import Dense
from tensorflow.keras.utils import to_categorical

In [5]:
fashion_mnist = tf.keras.datasets.fashion_mnist

(train_images, train_labels), (test_images, test_labels) = fashion_mnist.load_data()

In [6]:
train_images = (train_images / 255) - 1
test_images = (test_images / 255) - 1

In [7]:
train_images = train_images.reshape((-1, 784))
test_images = test_images.reshape((-1, 784))

print(train_images.shape) 
print(test_images.shape)  

(60000, 784)
(10000, 784)


In [8]:
model = Sequential([
  Dense(64, activation='relu', input_shape=(784,)),
  Dense(64, activation='relu'),
  Dense(64, activation='relu'),
  Dense(10, activation='softmax'),
])

In [9]:
model.compile(loss='categorical_crossentropy',
             optimizer='adam',
             metrics=['accuracy'])

In [10]:
model.fit(
  train_images, # training data
  to_categorical(train_labels),
  epochs=30,
  batch_size=32,
)

Epoch 1/30
60000/60000 [==============================] - 26s 429us/step - loss: 0.6928 - accuracy: 0.7416
Epoch 2/30
60000/60000 [==============================] - 26s 428us/step - loss: 0.5753 - accuracy: 0.7959
Epoch 3/30
60000/60000 [==============================] - 25s 422us/step - loss: 0.5586 - accuracy: 0.8038
Epoch 4/30
60000/60000 [==============================] - 25s 421us/step - loss: 0.5471 - accuracy: 0.8071
Epoch 5/30
60000/60000 [==============================] - 25s 421us/step - loss: 0.5379 - accuracy: 0.8113
Epoch 6/30
60000/60000 [==============================] - 26s 427us/step - loss: 0.5405 - accuracy: 0.8120
Epoch 7/30
60000/60000 [==============================] - 25s 422us/step - loss: 0.5302 - accuracy: 0.8128
Epoch 8/30
60000/60000 [==============================] - 26s 427us/step - loss: 0.5263 - accuracy: 0.8150s
Epoch 9/30
60000/60000 [==============================] - 26s 432us/step - loss: 0.5184 - accuracy: 0.8181s - loss: 0.5189 - accura
Epoch 10/30

In [28]:
model.evaluate(
  test_images,
  to_categorical(test_labels)
#Lecture:[Perte, Precision finale]

313/313 [==============================] - 0s 399us/step - loss: 0.3856 - accuracy: 0.8685


[0.3856329321861267, 0.8684999942779541]

In [29]:
# Pense bête X et Y:
# (train_images, train_labels), (test_images, test_labels)

In [30]:
#Prédiction des 5 premères images test.
predictions = model.predict(test_images)

# Impression du modèle de prédiction.
print(np.argmax(predictions, axis=1))

# Vérification de la prédiction
print(test_labels) 

[9 2 1 ... 8 1 5]
[9 2 1 ... 8 1 5]


In [31]:
#Matrice de confusion
matrix = confusion_matrix(test_labels, np.argmax(predictions, axis=1))
print(matrix)

[[778   0  21  31   6   6 145   2  11   0]
 [  1 968   2  20   4   0   2   0   3   0]
 [ 13   1 796  14 102   2  68   1   3   0]
 [ 11  13  15 872  53   3  26   1   6   0]
 [  1   1  87  21 811   0  73   0   6   0]
 [  0   0   0   1   0 898   0  84   0  17]
 [ 90   0  83  28  64   7 714   0  14   0]
 [  0   0   0   0   0   3   0 988   0   9]
 [  6   1   2   4   5   3  10   8 961   0]
 [  1   0   0   0   0  10   0  90   0 899]]


In [32]:
# précision tp / (tp + fp)
precision = precision_score(test_labels, np.argmax(predictions, axis=1),average='micro')
                                           
print('Precision: %f' % precision)


Precision: 0.868500


In [33]:
recall = recall_score(test_labels, np.argmax(predictions, axis=1),average='micro')
print('Recall: %f' % recall)

Recall: 0.868500
